test_that("draw obeys its contract (with vgam)", {
  withr::local_seed(0)
  dts <- sample(c("A", "B", "C"), 1000, replace = TRUE)
  y <- ifelse(runif(length(dts)) > 0.5, c(dts[-1], sample(c("A", "B", "C"), 1)), c(dts[-c(1, 2)], sample(c("A", "B", "C"), 2, replace = TRUE)))
  y <- as.factor(ifelse(runif(length(dts)) > 0.2, y, sample(c("A", "B", "C"), length(dts), replace = TRUE)))
  df_y <- data.frame(y = y)
  model <- covlmc(dts, df_y, alpha = 0.01, min_size = 5)
  expect_snapshot_output(draw(model, model = NULL, p_value = FALSE))
  expect_snapshot_output(draw(prune(model, 0.0001)))
  skip_on_ci()
  expect_snapshot_output(draw(model))
  expect_snapshot_output(draw(model, digits = 3))
  expect_snapshot_output(draw(model, model = NULL, digits = 2))
  expect_snapshot_output(draw(model, p_value = FALSE, digits = 1))
})

test_that("draw obeys its contract (with nnet)", {
  withr::local_seed(0)
  withr::local_options(mixvlmc.predictive = "multinom")
  dts <- sample(c("A", "B", "C"), 1000, replace = TRUE)
  y <- ifelse(runif(length(dts)) > 0.5, c(dts[-1], sample(c("A", "B", "C"), 1)), c(dts[-c(1, 2)], sample(c("A", "B", "C"), 2, replace = TRUE)))
  y <- as.factor(ifelse(runif(length(dts)) > 0.2, y, sample(c("A", "B", "C"), length(dts), replace = TRUE)))
  df_y <- data.frame(y = y)
  model <- covlmc(dts, df_y, alpha = 0.01, min_size = 5)
  expect_snapshot_output(draw(model))
  expect_snapshot_output(draw(model, digits = 3))
  expect_snapshot_output(draw(model, model = NULL, digits = 2))
  expect_snapshot_output(draw(model, p_value = FALSE, digits = 1))
})
