# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find a double just after another one
#'
#' This function returns a vector of values that are the "just after" the ones
#' given in input: a is just after b is a is the smallest double strictly
#' larger than b. This is implement with the \code{nextafter} C++ function.
#'
#' @param x vector of values
#' @return vector of just after values
#' @noRd
#'
after <- function(x) {
    .Call('_mixvlmc_after', PACKAGE = 'mixvlmc', x)
}

#' Find a double just before another one
#'
#' This function returns a vector of values that are the "just before" the ones
#' given in input: a is just before b is a is the largest double strictly
#' smaller than b. This is implement with the \code{nextafter} C++ function.
#'
#' @param x vector of values
#' @return vector of just before values
#' @noRd
#'
before <- function(x) {
    .Call('_mixvlmc_before', PACKAGE = 'mixvlmc', x)
}

forward_match_all_ctx_counts <- function(x, nb_vals, depth = 0L, nv_from = NULL) {
    .Call('_mixvlmc_forward_match_all_ctx_counts', PACKAGE = 'mixvlmc', x, nb_vals, depth, nv_from)
}

forward_match_all_ctx_counts_multi <- function(xs, nb_vals, depth, nvs_from, weights) {
    .Call('_mixvlmc_forward_match_all_ctx_counts_multi', PACKAGE = 'mixvlmc', xs, nb_vals, depth, nvs_from, weights)
}

kl_crit <- function(p, q) {
    .Call('_mixvlmc_kl_crit', PACKAGE = 'mixvlmc', p, q)
}

mixvlmc_sample <- function(p, n) {
    .Call('_mixvlmc_mixvlmc_sample', PACKAGE = 'mixvlmc', p, n)
}

mixvlmc_sample2 <- function(p, n) {
    .Call('_mixvlmc_mixvlmc_sample2', PACKAGE = 'mixvlmc', p, n)
}

extptr_is_null <- function(ptr) {
    .Call('_mixvlmc_extptr_is_null', PACKAGE = 'mixvlmc', ptr)
}

